In [168]:
import pandas as pd

In [169]:
player_box_score_stats = pd.read_excel("data/usports_stats_data.xlsx")
player_box_score_stats

,Player,Season,GP-GS,Mins,MPG,3 Pt_1,3 Pt_2,Field Goals_1,Field Goals_2,Free Throws_1,Free Throws_2,Rebounds_1,Rebounds_2,PF,AS,TO,BL,ST,Points_1,Points_2
0,Khalid Abdel-Gabar,2013-14,27-11,607,22.5,27-75,36.0,91-205,44.4,20-32,62.5,107,4.0,49.0,54.0,36.0,6.0,50.0,229,8.5
1,Khalid Abdel-Gabar,2014-15,30-30,905,30.2,53-163,32.5,146-368,39.7,43-67,64.2,115,3.8,47.0,100.0,60.0,3.0,41.0,388,12.9
2,Khalid Abdel-Gabar,Total,57-41,1512,26.5,80-238,33.6,237-573,41.4,63-99,63.6,222,3.9,96.0,154.0,96.0,9.0,91.0,617,10.8
3,Jamil Abiad,2009-10,23-0,254,11.0,21-61,34.4,32-86,37.2,6-10,60.0,32,1.4,32.0,14.0,31.0,NaN,13.0,91,4.0
4,Jamil Abiad,2012-13,12-0,139,11.6,4-18,22.2,11-33,33.3,3-5,60.0,15,1.2,16.0,7.0,4.0,NaN,5.0,29,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3667,Kristian Zjak,2018-19,16-0,141,8.8,0-0,0.0,24-43,55.8,11-22,50.0,40,2.5,16.0,5.0,10.0,4.0,NaN,59,3.7
3668,Kristian Zjak,Total,37-8,465,12.6,0-0,0.0,54-98,55.1,17-40,42.5,133,3.6,59.0,15.0,38.0,17.0,4.0,125,3.4
3669,Jim Zoet,1976-77,33,0,0.0,NaN,NaN,230-472,48.7,85-109,78.0,465,14.1,109.0,NaN,61.0,NaN,NaN,545,16.5
3670,Jim Zoet,1977-78,34,0,0.0,NaN,NaN,314-568,55.3,100-154,64.9,494,14.5,105.0,NaN,95.0,NaN,NaN,728,21.4
3671,Jim Zoet,Total,67,0,0.0,NaN,NaN,544-1040,52.3,185-263,70.3,959,14.3,214.0,NaN,156.0,NaN,NaN,1273,19.0

In [170]:
usports_to_pro_summary = pd.read_excel("data/usports_players_to_pro_summary.xlsx")

# Merge with usports_to_pro_summary
df = player_box_score_stats.merge(
    usports_to_pro_summary[["Player", "Position", "Hometown", "U Sports Team"]],
    on="Player",
    how="left"
)

cols = (
    ["Player", "Position", "Hometown", "U Sports Team"]
    + [c for c in df.columns if c not in ["Player", "Position", "Hometown", "U Sports Team"]]
)

df = df[cols]
df

,Player,Position,Hometown,U Sports Team,Season,GP-GS,Mins,MPG,3 Pt_1,3 Pt_2,...,Free Throws_2,Rebounds_1,Rebounds_2,PF,AS,TO,BL,ST,Points_1,Points_2
0,Khalid Abdel-Gabar,Guard 6-2,"Mississauga, ON",Windsor,2013-14,27-11,607,22.5,27-75,36.0,...,62.5,107,4.0,49.0,54.0,36.0,6.0,50.0,229,8.5
1,Khalid Abdel-Gabar,Guard 6-2,"Mississauga, ON",Windsor,2014-15,30-30,905,30.2,53-163,32.5,...,64.2,115,3.8,47.0,100.0,60.0,3.0,41.0,388,12.9
2,Khalid Abdel-Gabar,Guard 6-2,"Mississauga, ON",Windsor,Total,57-41,1512,26.5,80-238,33.6,...,63.6,222,3.9,96.0,154.0,96.0,9.0,91.0,617,10.8
3,Jamil Abiad,Guard 5-11,"Ottawa, ON",Bishop's,2009-10,23-0,254,11.0,21-61,34.4,...,60.0,32,1.4,32.0,14.0,31.0,NaN,13.0,91,4.0
4,Jamil Abiad,Guard 5-11,"Ottawa, ON",Bishop's,2012-13,12-0,139,11.6,4-18,22.2,...,60.0,15,1.2,16.0,7.0,4.0,NaN,5.0,29,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,Forward 6-7,"Point Cook, Australia",Mount Royal,2018-19,16-0,141,8.8,0-0,0.0,...,50.0,40,2.5,16.0,5.0,10.0,4.0,NaN,59,3.7
3676,Kristian Zjak,Forward 6-7,"Point Cook, Australia",Mount Royal,Total,37-8,465,12.6,0-0,0.0,...,42.5,133,3.6,59.0,15.0,38.0,17.0,4.0,125,3.4
3677,Jim Zoet,Centre 7-1,"Port Perry, ON",Lakehead,1976-77,33,0,0.0,NaN,NaN,...,78.0,465,14.1,109.0,NaN,61.0,NaN,NaN,545,16.5
3678,Jim Zoet,Centre 7-1,"Port Perry, ON",Lakehead,1977-78,34,0,0.0,NaN,NaN,...,64.9,494,14.5,105.0,NaN,95.0,NaN,NaN,728,21.4
3679,Jim Zoet,Centre 7-1,"Port Perry, ON",Lakehead,Total,67,0,0.0,NaN,NaN,...,70.3,959,14.3,214.0,NaN,156.0,NaN,NaN,1273,19.0

In [171]:
# Drop Unnecessary Columns
df = df.drop(columns=["Mins", "Rebounds_1", "Points_1"])
df

,Player,Position,Hometown,U Sports Team,Season,GP-GS,MPG,3 Pt_1,3 Pt_2,Field Goals_1,Field Goals_2,Free Throws_1,Free Throws_2,Rebounds_2,PF,AS,TO,BL,ST,Points_2
0,Khalid Abdel-Gabar,Guard 6-2,"Mississauga, ON",Windsor,2013-14,27-11,22.5,27-75,36.0,91-205,44.4,20-32,62.5,4.0,49.0,54.0,36.0,6.0,50.0,8.5
1,Khalid Abdel-Gabar,Guard 6-2,"Mississauga, ON",Windsor,2014-15,30-30,30.2,53-163,32.5,146-368,39.7,43-67,64.2,3.8,47.0,100.0,60.0,3.0,41.0,12.9
2,Khalid Abdel-Gabar,Guard 6-2,"Mississauga, ON",Windsor,Total,57-41,26.5,80-238,33.6,237-573,41.4,63-99,63.6,3.9,96.0,154.0,96.0,9.0,91.0,10.8
3,Jamil Abiad,Guard 5-11,"Ottawa, ON",Bishop's,2009-10,23-0,11.0,21-61,34.4,32-86,37.2,6-10,60.0,1.4,32.0,14.0,31.0,NaN,13.0,4.0
4,Jamil Abiad,Guard 5-11,"Ottawa, ON",Bishop's,2012-13,12-0,11.6,4-18,22.2,11-33,33.3,3-5,60.0,1.2,16.0,7.0,4.0,NaN,5.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,Forward 6-7,"Point Cook, Australia",Mount Royal,2018-19,16-0,8.8,0-0,0.0,24-43,55.8,11-22,50.0,2.5,16.0,5.0,10.0,4.0,NaN,3.7
3676,Kristian Zjak,Forward 6-7,"Point Cook, Australia",Mount Royal,Total,37-8,12.6,0-0,0.0,54-98,55.1,17-40,42.5,3.6,59.0,15.0,38.0,17.0,4.0,3.4
3677,Jim Zoet,Centre 7-1,"Port Perry, ON",Lakehead,1976-77,33,0.0,NaN,NaN,230-472,48.7,85-109,78.0,14.1,109.0,NaN,61.0,NaN,NaN,16.5
3678,Jim Zoet,Centre 7-1,"Port Perry, ON",Lakehead,1977-78,34,0.0,NaN,NaN,314-568,55.3,100-154,64.9,14.5,105.0,NaN,95.0,NaN,NaN,21.4
3679,Jim Zoet,Centre 7-1,"Port Perry, ON",Lakehead,Total,67,0.0,NaN,NaN,544-1040,52.3,185-263,70.3,14.3,214.0,NaN,156.0,NaN,NaN,19.0

In [172]:
# Split Position into Position and Height
split_cols = df["Position"].str.split(" ", n=1, expand=True)
split_cols[0] = split_cols[0].replace({"Guard": "G", "Forward": "F", "Centre": "C", "Wing": "G/F", "Guard/Wing": "G/F", "Ailier": "SF", "Arriere": "SG", "Meneur": "PG", "Centre/Forward": "C/F", "Garde": "G", "Guard-Forward": "G/F", "Guard/Forward": "G/F", "Point Guard": "PG", "Post": "F/C"}, regex=False)
index = df.columns.get_loc("Position")
df["Position"] = split_cols[0]
df.insert(index + 1, "Height", split_cols[1])
df

,Player,Position,Height,Hometown,U Sports Team,Season,GP-GS,MPG,3 Pt_1,3 Pt_2,...,Field Goals_2,Free Throws_1,Free Throws_2,Rebounds_2,PF,AS,TO,BL,ST,Points_2
0,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2013-14,27-11,22.5,27-75,36.0,...,44.4,20-32,62.5,4.0,49.0,54.0,36.0,6.0,50.0,8.5
1,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2014-15,30-30,30.2,53-163,32.5,...,39.7,43-67,64.2,3.8,47.0,100.0,60.0,3.0,41.0,12.9
2,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,Total,57-41,26.5,80-238,33.6,...,41.4,63-99,63.6,3.9,96.0,154.0,96.0,9.0,91.0,10.8
3,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2009-10,23-0,11.0,21-61,34.4,...,37.2,6-10,60.0,1.4,32.0,14.0,31.0,NaN,13.0,4.0
4,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2012-13,12-0,11.6,4-18,22.2,...,33.3,3-5,60.0,1.2,16.0,7.0,4.0,NaN,5.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,2018-19,16-0,8.8,0-0,0.0,...,55.8,11-22,50.0,2.5,16.0,5.0,10.0,4.0,NaN,3.7
3676,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,Total,37-8,12.6,0-0,0.0,...,55.1,17-40,42.5,3.6,59.0,15.0,38.0,17.0,4.0,3.4
3677,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1976-77,33,0.0,NaN,NaN,...,48.7,85-109,78.0,14.1,109.0,NaN,61.0,NaN,NaN,16.5
3678,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1977-78,34,0.0,NaN,NaN,...,55.3,100-154,64.9,14.5,105.0,NaN,95.0,NaN,NaN,21.4
3679,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,Total,67,0.0,NaN,NaN,...,52.3,185-263,70.3,14.3,214.0,NaN,156.0,NaN,NaN,19.0

In [173]:
# Split GP-GS column
split_cols = df["GP-GS"].str.split("-", n=1, expand=True)
gp_gs_index = df.columns.get_loc("GP-GS")
df.insert(gp_gs_index + 1, "GP", pd.to_numeric(split_cols[0], errors="coerce").astype("Int64"))
df.insert(gp_gs_index + 2, "GS", pd.to_numeric(split_cols[1], errors="coerce").astype("Int64"))
df = df.drop(columns=["GP-GS"])
df

,Player,Position,Height,Hometown,U Sports Team,Season,GP,GS,MPG,3 Pt_1,...,Field Goals_2,Free Throws_1,Free Throws_2,Rebounds_2,PF,AS,TO,BL,ST,Points_2
0,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2013-14,27,11,22.5,27-75,...,44.4,20-32,62.5,4.0,49.0,54.0,36.0,6.0,50.0,8.5
1,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2014-15,30,30,30.2,53-163,...,39.7,43-67,64.2,3.8,47.0,100.0,60.0,3.0,41.0,12.9
2,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,Total,57,41,26.5,80-238,...,41.4,63-99,63.6,3.9,96.0,154.0,96.0,9.0,91.0,10.8
3,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2009-10,23,0,11.0,21-61,...,37.2,6-10,60.0,1.4,32.0,14.0,31.0,NaN,13.0,4.0
4,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2012-13,12,0,11.6,4-18,...,33.3,3-5,60.0,1.2,16.0,7.0,4.0,NaN,5.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,2018-19,16,0,8.8,0-0,...,55.8,11-22,50.0,2.5,16.0,5.0,10.0,4.0,NaN,3.7
3676,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,Total,37,8,12.6,0-0,...,55.1,17-40,42.5,3.6,59.0,15.0,38.0,17.0,4.0,3.4
3677,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1976-77,33,<NA>,0.0,NaN,...,48.7,85-109,78.0,14.1,109.0,NaN,61.0,NaN,NaN,16.5
3678,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1977-78,34,<NA>,0.0,NaN,...,55.3,100-154,64.9,14.5,105.0,NaN,95.0,NaN,NaN,21.4
3679,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,Total,67,<NA>,0.0,NaN,...,52.3,185-263,70.3,14.3,214.0,NaN,156.0,NaN,NaN,19.0

In [174]:
# Split 3PT column
split_cols = df["3 Pt_1"].str.split("-", n=1, expand=True)
index = df.columns.get_loc("3 Pt_1")
df.insert(index + 1, "3PM", pd.to_numeric(split_cols[0], errors="coerce").astype("Int64"))
df.insert(index + 2, "3PA", pd.to_numeric(split_cols[1], errors="coerce").astype("Int64"))
df = df.drop(columns=["3 Pt_1"])

# Rename 3PT% Column
df = df.rename(columns={"3 Pt_2": "3P%"})
df["3P%"] = df["3P%"].astype(float)
df

,Player,Position,Height,Hometown,U Sports Team,Season,GP,GS,MPG,3PM,...,Field Goals_2,Free Throws_1,Free Throws_2,Rebounds_2,PF,AS,TO,BL,ST,Points_2
0,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2013-14,27,11,22.5,27,...,44.4,20-32,62.5,4.0,49.0,54.0,36.0,6.0,50.0,8.5
1,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2014-15,30,30,30.2,53,...,39.7,43-67,64.2,3.8,47.0,100.0,60.0,3.0,41.0,12.9
2,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,Total,57,41,26.5,80,...,41.4,63-99,63.6,3.9,96.0,154.0,96.0,9.0,91.0,10.8
3,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2009-10,23,0,11.0,21,...,37.2,6-10,60.0,1.4,32.0,14.0,31.0,NaN,13.0,4.0
4,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2012-13,12,0,11.6,4,...,33.3,3-5,60.0,1.2,16.0,7.0,4.0,NaN,5.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,2018-19,16,0,8.8,0,...,55.8,11-22,50.0,2.5,16.0,5.0,10.0,4.0,NaN,3.7
3676,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,Total,37,8,12.6,0,...,55.1,17-40,42.5,3.6,59.0,15.0,38.0,17.0,4.0,3.4
3677,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1976-77,33,<NA>,0.0,<NA>,...,48.7,85-109,78.0,14.1,109.0,NaN,61.0,NaN,NaN,16.5
3678,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1977-78,34,<NA>,0.0,<NA>,...,55.3,100-154,64.9,14.5,105.0,NaN,95.0,NaN,NaN,21.4
3679,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,Total,67,<NA>,0.0,<NA>,...,52.3,185-263,70.3,14.3,214.0,NaN,156.0,NaN,NaN,19.0

In [175]:
# Split Field Goals column
split_cols = df["Field Goals_1"].str.split("-", n=1, expand=True)
index = df.columns.get_loc("Field Goals_1")
df.insert(index + 1, "FGM", pd.to_numeric(split_cols[0], errors="coerce").astype("Int64"))
df.insert(index + 2, "FGA", pd.to_numeric(split_cols[1], errors="coerce").astype("Int64"))
df = df.drop(columns=["Field Goals_1"])

# Rename FG% Column
df = df.rename(columns={"Field Goals_2": "FG%"})
df["FG%"] = df["FG%"].astype(float)
df[["Player", "FGM", "FGA", "FG%"]].head(20)

                Player  FGM  FGA   FG%
0   Khalid Abdel-Gabar   91  205  44.4
1   Khalid Abdel-Gabar  146  368  39.7
2   Khalid Abdel-Gabar  237  573  41.4
3          Jamil Abiad   32   86  37.2
4          Jamil Abiad   11   33  33.3
5          Jamil Abiad   28   73  38.4
6          Jamil Abiad   71  192  37.0
7   Michael Acheampong  109  249  43.8
8   Michael Acheampong  117  316  37.0
9   Michael Acheampong  226  565  40.0
10     Daniel Adediran   14   29  48.3
11     Daniel Adediran   74  143  51.7
12     Daniel Adediran   50   78  64.1
13     Daniel Adediran   69  137  50.4
14     Daniel Adediran    0    0   0.0
15     Daniel Adediran  207  387  53.5
16         Bruce Adjei    9   15  60.0
17          Seth Adler   81  213  38.0
18          Seth Adler   81  200  40.5
19          Seth Adler   98  223  43.9

In [176]:
# Split Field Throw column
split_cols = df["Free Throws_1"].str.split("-", n=1, expand=True)
index = df.columns.get_loc("Free Throws_1")
df.insert(index + 1, "FTM", pd.to_numeric(split_cols[0], errors="coerce").astype("Int64"))
df.insert(index + 2, "FTA", pd.to_numeric(split_cols[1], errors="coerce").astype("Int64"))
df = df.drop(columns=["Free Throws_1"])

# Rename FT% Column
df = df.rename(columns={"Free Throws_2": "FT%"})
df["FT%"] = df["FT%"].astype(float)
df[["Player", "FTM", "FTA", "FT%"]].head(20)

                Player  FTM  FTA   FT%
0   Khalid Abdel-Gabar   20   32  62.5
1   Khalid Abdel-Gabar   43   67  64.2
2   Khalid Abdel-Gabar   63   99  63.6
3          Jamil Abiad    6   10  60.0
4          Jamil Abiad    3    5  60.0
5          Jamil Abiad    1    2  50.0
6          Jamil Abiad   10   17  58.8
7   Michael Acheampong   42   63  66.7
8   Michael Acheampong   86  109  78.9
9   Michael Acheampong  128  172  74.4
10     Daniel Adediran    4    7  57.1
11     Daniel Adediran   33   47  70.2
12     Daniel Adediran   22   33  66.7
13     Daniel Adediran   27   45  60.0
14     Daniel Adediran    0    0   0.0
15     Daniel Adediran   86  132  65.2
16         Bruce Adjei    7   15  46.7
17          Seth Adler   73   96  76.0
18          Seth Adler   55   75  73.3
19          Seth Adler   62   83  74.7

In [177]:
# Rename Columns
df = df.rename(columns={"Rebounds_2": "REB", "Points_2": "PPG", "AS": "AST", "TO": "TOV", "BL": "BLK", "ST": "STL"})
df

,Player,Position,Height,Hometown,U Sports Team,Season,GP,GS,MPG,3PM,...,FTM,FTA,FT%,REB,PF,AST,TOV,BLK,STL,PPG
0,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2013-14,27,11,22.5,27,...,20,32,62.5,4.0,49.0,54.0,36.0,6.0,50.0,8.5
1,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2014-15,30,30,30.2,53,...,43,67,64.2,3.8,47.0,100.0,60.0,3.0,41.0,12.9
2,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,Total,57,41,26.5,80,...,63,99,63.6,3.9,96.0,154.0,96.0,9.0,91.0,10.8
3,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2009-10,23,0,11.0,21,...,6,10,60.0,1.4,32.0,14.0,31.0,NaN,13.0,4.0
4,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2012-13,12,0,11.6,4,...,3,5,60.0,1.2,16.0,7.0,4.0,NaN,5.0,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,2018-19,16,0,8.8,0,...,11,22,50.0,2.5,16.0,5.0,10.0,4.0,NaN,3.7
3676,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,Total,37,8,12.6,0,...,17,40,42.5,3.6,59.0,15.0,38.0,17.0,4.0,3.4
3677,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1976-77,33,<NA>,0.0,<NA>,...,85,109,78.0,14.1,109.0,NaN,61.0,NaN,NaN,16.5
3678,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1977-78,34,<NA>,0.0,<NA>,...,100,154,64.9,14.5,105.0,NaN,95.0,NaN,NaN,21.4
3679,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,Total,67,<NA>,0.0,<NA>,...,185,263,70.3,14.3,214.0,NaN,156.0,NaN,NaN,19.0

In [178]:
# Calculating per game stats
df["PF"] = (df["PF"] / df["GP"]).round(1)
df["AST"] = (df["AST"] / df["GP"]).round(1)
df["TOV"] = (df["TOV"] / df["GP"]).round(1)
df["BLK"] = (df["BLK"] / df["GP"]).round(1)
df["STL"] = (df["STL"] / df["GP"]).round(1)
df

,Player,Position,Height,Hometown,U Sports Team,Season,GP,GS,MPG,3PM,...,FTM,FTA,FT%,REB,PF,AST,TOV,BLK,STL,PPG
0,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2013-14,27,11,22.5,27,...,20,32,62.5,4.0,1.8,2.0,1.3,0.2,1.9,8.5
1,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,2014-15,30,30,30.2,53,...,43,67,64.2,3.8,1.6,3.3,2.0,0.1,1.4,12.9
2,Khalid Abdel-Gabar,G,6-2,"Mississauga, ON",Windsor,Total,57,41,26.5,80,...,63,99,63.6,3.9,1.7,2.7,1.7,0.2,1.6,10.8
3,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2009-10,23,0,11.0,21,...,6,10,60.0,1.4,1.4,0.6,1.3,<NA>,0.6,4.0
4,Jamil Abiad,G,5-11,"Ottawa, ON",Bishop's,2012-13,12,0,11.6,4,...,3,5,60.0,1.2,1.3,0.6,0.3,<NA>,0.4,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3675,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,2018-19,16,0,8.8,0,...,11,22,50.0,2.5,1.0,0.3,0.6,0.2,<NA>,3.7
3676,Kristian Zjak,F,6-7,"Point Cook, Australia",Mount Royal,Total,37,8,12.6,0,...,17,40,42.5,3.6,1.6,0.4,1.0,0.5,0.1,3.4
3677,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1976-77,33,<NA>,0.0,<NA>,...,85,109,78.0,14.1,3.3,<NA>,1.8,<NA>,<NA>,16.5
3678,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,1977-78,34,<NA>,0.0,<NA>,...,100,154,64.9,14.5,3.1,<NA>,2.8,<NA>,<NA>,21.4
3679,Jim Zoet,C,7-1,"Port Perry, ON",Lakehead,Total,67,<NA>,0.0,<NA>,...,185,263,70.3,14.3,3.2,<NA>,2.3,<NA>,<NA>,19.0

In [179]:
df.to_excel("data/cleaned_usports_player_box_score_stats.xlsx", index=False, engine="openpyxl")